# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x0b\x46ileService\" \n\x0b\x46ileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"g\n\tFileChunk\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x12\n\ntotal_size\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63hunk_number\x18\x04 \x01(\x05\x12\x0f\n\x07is_last\x18\x05 \x01(\x08\x32R\n\x0c\x46ileStreamer\x12\x42\n\x0c\x44ownloadFile\x12\x18.FileService.FileRequest\x1a\x16.FileService.FileChunk0\x01\x42\x17\xaa\x02\x14TestGrpc.FileServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\024TestGrpc.FileService'
  _globals['_FILEREQUEST']._serialized_start=27
  _globals['_FILEREQUEST']._serialized_end=59
  _globals['_FILECHUNK']._serialized_start=61
  _globals['_FILECHUNK']._serialized_end=164
  _globals['_FILESTREAMER']._serialized_start=166
  _globals['_FILESTREAMER']._serialized_end=248
# @@protoc_insertion_point(module_scope)
