# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'greet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"8\n\x0b\x44\x61taRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\"0\n\tDataReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0breceived_id\x18\x02 \x01(\x05\x32o\n\x07Greeter\x12\x32\n\x08SayHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply\x12\x30\n\x08SendData\x12\x12.greet.DataRequest\x1a\x10.greet.DataReplyB\x11\xaa\x02\x0eTestGrpc.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016TestGrpc.proto'
  _globals['_HELLOREQUEST']._serialized_start=22
  _globals['_HELLOREQUEST']._serialized_end=50
  _globals['_HELLOREPLY']._serialized_start=52
  _globals['_HELLOREPLY']._serialized_end=81
  _globals['_DATAREQUEST']._serialized_start=83
  _globals['_DATAREQUEST']._serialized_end=139
  _globals['_DATAREPLY']._serialized_start=141
  _globals['_DATAREPLY']._serialized_end=189
  _globals['_GREETER']._serialized_start=191
  _globals['_GREETER']._serialized_end=302
# @@protoc_insertion_point(module_scope)
